### ISSUE TITLE
Can't select form background color

### ISSUE THREAD

**Issue by razvanaldea89** [ColorlibHQ/colorlib-login-customizer#126] opened 2020-10-12 06:30 UTC
Select a template, go to General Form Options and try to change Form Background Color. The color picker appears but selecting one color doesn't work.

**Comment by TeoAlex** [comment] 2024-03-21 08:36
Seems to be working as intended, maybe it was fixed in a previous update or it's related to this issue https://github.com/ColorlibHQ/colorlib-login-customizer/issues/136 that was fixed

**Closed** 2024-03-21 09:29 UTC
Labels: bug, can't replicate
