### ISSUE TITLE
option to add both a logo and text

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/colorlib-login-customizer#85] opened 2019-01-03 10:40 UTC
Client feedback:
1. As is you can have a choice of a a text or image logo. I found myself wanting both.

**Comment by razvanaldea89** [comment] 2019-07-25 15:44
This will be possible when we move the login page to a template.

**Comment by razvanaldea89** [comment] 2020-05-21 09:50
Duplicate of #80

**Closed** 2020-05-21 10:03 UTC
Labels: duplicate, enhancement
