### ISSUE TITLE
PHP 8 crash

### ISSUE THREAD

**Issue by beatricelucaci** [ColorlibHQ/colorlib-login-customizer#146] opened 2021-06-15 13:40 UTC
After upgrading the PHP to version 8, I cannot reach the login page of WP.

I just see this message:
There has been a critical error on this website.
Learn more about troubleshooting WordPress.

https://wordpress.org/support/topic/php-8-crash/

**Comment by TeoAlex** [comment] 2024-03-20 12:27
Tested with php v8.1 and v8.3 and could not reproduce. It was most likely something specific to the user's server. I will close this and if we get any more reports, we can reopen.

**Closed by TeoAlex** 2024-03-20 12:27 UTC
