### ISSUE TITLE
check PHP deprecation notices

### ISSUE THREAD

**Issue by beatricelucaci** [ColorlibHQ/colorlib-login-customizer#167] opened 2023-12-11 12:00 UTC
The version bump is ok but I will ask you to check PHP deprecation notices too.

Creation of dynamic property Colorlib_Login_Customizer::$base is deprecated wp-content/plugins/colorlib-login-customizer/includes/class-colorlib-login-customizer.php:98

Creation of dynamic property Colorlib_Login_Customizer_CSS_Customization::$key_name is deprecated wp-content/plugins/colorlib-login-customizer/includes/lib/class-colorlib-login-customizer-css-customization.php:30

Creation of dynamic property Colorlib_Login_Customizer::$key_name is deprecated wp-content/plugins/colorlib-login-customizer/includes/class-colorlib-login-customizer.php:99

https://wordpress.org/support/topic/bump-up-the-version-2/

**Comment by TeoAlex** [comment] 2024-03-20 08:52
duplicate of https://github.com/ColorlibHQ/colorlib-login-customizer/issues/169

**Closed by TeoAlex** 2024-03-20 08:52 UTC
